import Head from "next/head";
import Header from "../components/Header";
import Homepage from "../pages/home";
import About from "./about";
import Skill from "./skill";

export default function Home() {
  return (
    <di>
      <Head>
        <title>NATCHANON-Homepage </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-[#181818] transition-all duration-100 w-screen bg-slate-200">
        <Header />
        <Homepage />
        <About />
        <Skill />
      </main>
    </di>
  );
}
